name: Deploy to azure.

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Clona el repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Lint (asegúrate que "lint" está definido en package.json)
      - name: Run Lint
        run: npm run lint

      # 5. Test (asegúrate que "test" está definido en package.json)
      - name: Run Tests
        run: npm test

      # 6. Build frontend
      - name: Build frontend
        run: npm run build

      # 7. Despliega a Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                       ${{ secrets.GITHUB_TOKEN }} # ya viene por defecto
          action:                           "upload"
          app_location:                     "/"       # carpeta raíz del front
          api_location:                     ""        # si no tienes Azure Functions, déjalo vacío
          output_location:                  "dist"    # donde Vite deja los archivos estáticos
